# Example zclip configuration file.

[debugging]
# 1024 * 1024 * 512 = 512MB. Might be useful to set for debugging purposes. 
# memory_limit = 536870912

[daemon]
# You can optionally specify a port here. Defaults to 48500.
bind_address = "127.0.0.1"

# Make sure the users accessing the socket are in the same group as the account
# running the daemon.

# unix_socket_address = "mycustom.sock"

# This can be relative to cwd of the daemon/client, or absolute.

# data_dir = "./zclip"

# A list of (internet) peers. Pubkeys can be copied over out of band, similar to SSH.
# A keypair is generated on first launch of the daemon.
[[daemon.peers]]
# As we can see, Bob is just a peer I made up for testing purposes.
nickname = "Bob"
pubkey = "Y+xygwe8zSCfUNBiVq6tmKPT/2Q1tzSfTfKU+5+5mVE="
addr = "127.0.0.1:48501"

[client]
# Same rules apply as above. This should probably match daemon.unix_socket_address.

# unix_socket_address = "mycustom.sock"
