// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 J. Hinchliffe (nullndvoid)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

//! Packet header definition.

const std = @import("std");

const DateTime = @import("../../DateTime.zig");
const Packet = @import("../Packet.zig");
const Id = Packet.Id;

/// This is generated by the sender of a message.
request_id: Id,
/// Unix timestamp. Could be used to see latency.
timestamp_ms: UnixTimestampMs,

pub const serde = .{
    .rename = .{ .timestamp_ms = "timestamp" },
};

pub const UnixTimestampMs = struct {
    val: i64,

    pub fn zerdeSerialize(self: UnixTimestampMs, serializer: anytype) !void {
        var buf: [DateTime.MAX_RFC3339_LENGTH]u8 = undefined;
        const timestamp = DateTime.fromMillis(self.val);
        const s = std.mem.print(&buf, "{f}", .{timestamp}) catch |e|
            std.debug.panic("Could not print timestamp to buffer! Why: {t}", .{e});

        try serializer.serializeString(s);
    }
};
