// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 J. Hinchliffe (nullndvoid)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

//! Packets for the Network protocol.

const std = @import("std");
const Io = std.Io;
const assert = std.debug.assert;

const clipboard = @import("clipboard");

const Packet = @This();

const Id = u64;

const ID_LEN = @sizeOf(Id);
const TAG_LEN = @sizeOf(u8);
const SLICE_PREFIX_LEN = @sizeOf(u32);
const HEADER_LEN = ID_LEN + @sizeOf(i64) + TAG_LEN;

pub const Header = struct {
    /// Unix timestamp. Could be used to see latency.
    timestamp_ms: i64,
    /// This is generated by the sender of a message.
    request_id: Id,
};

header: Header,
payload: Payload,

/// Returns the friendlier error message given an error.
pub fn errorMessage(err: ErrorTags) []const u8 {
    return switch (err) {
        .NoSuchId => "An ID was supplied in a request but did not exist.",
        else => "Invalid error tag set.",
    };
}

/// These are errors that can be returned across peer boundaries.
///
/// Although encoded as u8, the top bit is out of use as it is
/// used to check for the optional message included with an error.
pub const ErrorTags = enum(u8) {
    /// An ID was supplied in a request but did not exist.
    NoSuchId = 0,
    _,
};

comptime {
    for (@typeInfo(ErrorTags).@"enum".fields) |f| {
        if (f.value > 127) @compileError("Top error tag bit is reserved!");
    }
}

/// A chunk in messages which may be packetised.
pub const Chunk = struct {
    seq: u32,
    end: u32,
    bytes: []const u8,
};

pub const PayloadTag = enum(u8) {
    clip = 0,
    request_formats = 1,
    formats_response = 2,
    request_clip = 3,
    request_clip_response = 4,
    ok_response = 5,
    shutting_down = 6,
    err = 7,
    _,
};

/// If new commands are added in later versions, I shall prefix them with vN.
pub const Payload = union(PayloadTag) {
    /// A clipboard entry with default MIME type.
    clip: struct {
        /// Used to track the clip on that particular server.
        id: Id,
        mime_type: []const u8,
        chunk: Chunk,
    },
    /// Requests a list of formats for a clip of `id`.
    request_formats: Id,
    /// A list of formats for a clip of `id`.
    formats_response: struct {
        id: Id,
        formats: []ClipFormat,
    },
    /// A peer requests a clip of `id` and `format`.
    request_clip: struct {
        id: Id,
        format: ClipFormat,
    },
    /// This may be packetised, so there will be a seq of chunks.
    /// Last chunk may not occupy the total payload space.
    request_clip_response: struct {
        id: Id,
        format: ClipFormat,
        chunk: Chunk,
    },
    /// Sent back when the last operation completed successfully,
    /// but nothing need be returned.
    ///
    /// Contains the request ID of the relevant request.
    ///
    /// No one is actually expected to track more than the last one or
    /// two requests to check this is __actually__ unique.
    ///
    /// This is also sent when events like `clip` are sent as a ping/pong
    /// type of deal. Maybe this can be used for some kind of keepalive?
    ok_response: Id,
    /// Sent when the peer is shutting down, so all connected peers know to
    /// terminate their connections.
    shutting_down,
    /// Sent on errors.
    err: struct {
        tag: ErrorTags,
        /// For debugging purposes. May be displayed to the user.
        ///
        /// This will be displayed alongside the default message if present.
        extra_context: ?[]const u8,
    },
};

// Comptime check that Chunk fields are last. This encourages people to read and
// write chunks last in the below serialisation/deser code.
comptime {
    for (@typeInfo(Payload).@"union".fields) |uf| {
        const ti = @typeInfo(uf.type);
        if (ti != .@"struct") continue;
        const fields = ti.@"struct".fields;
        for (fields, 0..) |f, i| {
            if (f.type == Chunk and i != fields.len - 1)
                @compileError("Chunk must be the last field of Payload." ++ uf.name);
        }
    }
}

/// Reproduced from my clipboard-zig library because I want to roll my own
/// ser/deser.
const ClipType = enum(u8) {
    text = 0,
    html = 1,
    image = 2,
    file = 3,
    rtf = 4,
    other = 5,
    _,
};

/// Reproduced from my clipboard-zig library because I want to roll my own
/// ser/deser.
const ClipFormat = struct {
    fmt: ClipType,
    mime: []const u8,

    pub fn from(fmt: clipboard.Clip.Format) ClipFormat {
        const format: ClipType = switch (fmt.format) {
            .text => .text,
            .html => .html,
            .rtf => .rtf,
            .image => .image,
            .file => .file,
            .other => .other,
        };

        return .{
            .fmt = format,
            .mime = fmt.mime_type,
        };
    }
};

/// All integer values are sent in big endian network order.
///
/// Packets are assumed to be of the correct size, so we can
/// have a buffer allocated only once (per peer), which can
/// be used for all packets sent and recieved.
pub fn encode(packet: *const Packet, writer: *Io.Writer) !void {
    // Write the request id, timestamp, and tag.
    try writer.writeInt(Id, packet.header.request_id, .big);
    try writer.writeInt(i64, packet.header.timestamp_ms, .big);
    try writer.writeInt(u8, @intFromEnum(packet.payload), .big);

    switch (packet.payload) {
        .request_formats, .ok_response => |id| try writer.writeInt(Id, id, .big),
        .shutting_down => {},
        .err => |err| {
            // We set the upper bit to determine if there was an optional message.
            const opt = @as(u8, @intCast(@intFromBool(err.extra_context != null))) << 7;
            const tag: u8 = @intFromEnum(err.tag) | opt;

            try writer.writeInt(u8, tag, .big);

            if (err.extra_context) |ctx| {
                try writer.writeAll(ctx);
            }
        },
        .clip => |clip| {
            try writer.writeInt(Id, clip.id, .big);
            try writeByteSlice(writer, clip.mime_type);
            try writeChunk(writer, clip.chunk);
        },
        .request_clip => |rc| {
            try writer.writeInt(Id, rc.id, .big);
            try writeClipFormat(writer, rc.format);
        },
        .formats_response => |fmts| {
            try writer.writeInt(Id, fmts.id, .big);
            try writer.writeInt(u8, fmts.formats.len, .big);
            for (fmts.formats) |fmt| {
                try writeClipFormat(writer, fmt);
            }
        },
        .request_clip_response => |clip| {
            try writer.writeInt(Id, clip.id, .big);
            try writeClipFormat(writer, clip.format);
            try writeChunk(writer, clip.chunk);
        },
    }
}

/// Returns the on wire (serialised) size of a packet.
///
/// encodedSize(.{}) + body.len (i.e. chunk len) = encodedSize(packet_with_body)
/// so this may be called once and memoised when writing several chunks etc.
///
/// This invariant may be broken when adding new fields, so take care.
pub fn encodedSize(packet: *const Packet) usize {
    return HEADER_LEN + switch (packet.payload) {
        .clip => |clip| SLICE_PREFIX_LEN + clip.mime_type.len + ID_LEN + chunkSize(clip.chunk),
        .err => |err| TAG_LEN + if (err.extra_context) |ctx| ctx.len else 0,
        .request_formats, .ok_response => ID_LEN,
        .shutting_down => 0,
        .request_clip_response => |clip| ID_LEN + chunkSize(clip.chunk) + TAG_LEN + SLICE_PREFIX_LEN + clip.format.mime.len,
        // 1 byte length prefix is certainly fine.
        .formats_response => |fmts| ID_LEN + 1 + blk: {
            var overhead: usize = 0;
            for (fmts.formats) |fmt| {
                overhead += TAG_LEN + SLICE_PREFIX_LEN + fmt.mime.len;
            }

            break :blk overhead;
        },
        .request_clip => |req| ID_LEN + TAG_LEN + SLICE_PREFIX_LEN + req.format.mime.len,
    };
}

fn chunkSize(chunk: Chunk) usize {
    return chunk.bytes.len +
        @sizeOf(@TypeOf(chunk.end)) +
        @sizeOf(@TypeOf(chunk.seq));
}

inline fn writeClipFormat(writer: *Io.Writer, fmt: ClipFormat) !void {
    try writer.writeInt(u8, @intFromEnum(fmt.fmt), .big);
    try writeByteSlice(writer, fmt.mime);
}

/// Even a u32 is overkill but its alright for now.
inline fn writeByteSlice(writer: *Io.Writer, bytes: []const u8) !void {
    assert(bytes.len <= std.math.maxInt(u32));

    try writer.writeInt(u32, @intCast(bytes.len), .big);
    try writer.writeAll(bytes);
}

/// This assumes chunks are written last so we know how many bytes to read.
inline fn writeChunk(writer: *Io.Writer, chunk: Chunk) !void {
    try writer.writeInt(u32, chunk.seq, .big);
    try writer.writeInt(u32, chunk.end, .big);
    try writer.writeAll(chunk.bytes);
}

/// Returns (tag, should_read_slice).
inline fn decodeErrTag(err_tag: u8) struct { ErrorTags, bool } {
    const tag: ErrorTags = @enumFromInt(err_tag & 0x7f);
    const should_read_slice: bool = (err_tag & 0x80) != 0;

    return .{ tag, should_read_slice };
}
