// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 J. Hinchliffe (nullndvoid)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

//! Packets for the Network protocol.
//!
//! TODO: Packetise large payloads.

const std = @import("std");
const Io = std.Io;

const clipboard = @import("clipboard");
const ClipFormat = clipboard.Clip.Format;
const Serde = @import("serde");

const Packet = @This();

const Id = u64;

/// Unix timestamp. Could be used to see latency.
timestamp_ms: i64,
/// This is generated by the sender of a message.
request_id: Id,
payload: PayloadOrError,

/// Returns the friendlier error message given an error.
pub fn errorMessage(err: ErrorTags) []const u8 {
    return switch (err) {
        .NoSuchId => "An ID was supplied in a request but did not exist.",
    };
}

/// These are errors that can be returned across peer boundaries.
pub const ErrorTags = enum {
    /// An ID was supplied in a request but did not exist.
    NoSuchId,
};

/// A chunk in messages which may be packetised.
pub const Chunk = struct {
    seq: u32,
    end: u32,
    bytes: []const u8,
};

/// If new commands are added in later versions, I shall prefix them with vN.
pub const Payload = union(enum) {
    /// A clipboard entry with default MIME type.
    clip: struct {
        /// Used to track the clip on that particular server.
        id: Id,
        mime_type: []const u8,
        chunk: Chunk,
    },
    /// Requests a list of formats for a clip of `id`.
    request_formats: struct {
        id: Id,
    },
    /// A list of formats for a clip of `id`.
    formats_response: struct {
        id: Id,
        formats: []ClipFormat,
    },
    /// A peer requests a clip of `id` and `format`.
    request_clip: struct {
        id: Id,
        format: ClipFormat,
    },
    /// This may be packetised, so there will be a seq of chunks.
    /// Last chunk may not occupy the total payload space.
    request_clip_response: struct {
        id: Id,
        format: ClipFormat,
        chunk: Chunk,
    },
    /// Sent back when the last operation completed successfully,
    /// but nothing need be returned.
    ///
    /// Contains the request ID of the relevant request.
    ///
    /// No one is actually expected to track more than the last one or
    /// two requests to check this is __actually__ unique.
    ///
    /// This is also sent when events like `clip` are sent as a ping/pong
    /// type of deal. Maybe this can be used for some kind of keepalive?
    ok_response: Id,
    /// Sent when the peer is shutting down, so all connected peers know to
    /// terminate their connections.
    shutting_down,
};

pub const PayloadOrError = union(enum) {
    ok: Payload,
    err: struct {
        tag: ErrorTags,
        /// For debugging purposes. May be displayed to the user.
        ///
        /// This will be displayed alongside the default message if present.
        extra_context: ?[]const u8,
    },
};

fn init(io: Io, payload_or_error: PayloadOrError, request_id: u64) Packet {
    const ts = Io.Timestamp.now(io, .awake);
    const ts_ms = ts.toMilliseconds();

    return .{
        .payload = payload_or_error,
        .request_id = request_id,
        .timestamp_ms = ts_ms,
    };
}

/// Creates a packet with a payload.
pub fn initWithPayload(io: Io, request_id: u64, payload: Payload) Packet {
    return init(
        io,
        .{ .ok = payload },
        request_id,
    );
}

/// Creates a packet with an error.
pub fn initWithErr(
    io: Io,
    request_id: u64,
    err: ErrorTags,
    ctx: struct { extra: []const u8 = &.{} },
) Packet {
    return init(
        io,
        .{ .err = .{
            .tag = err,
            .extra_context = ctx.extra,
        } },
        request_id,
    );
}

/// Returns the difference between packet timestamp and the current one.
pub fn latency(self: *const Packet, io: Io) i64 {
    const current = Io.Timestamp.now(io, .awake).toMilliseconds();

    return self.timestamp_ms - current;
}

test "encode and decode" {
    const io = std.testing.io;
    const allocator = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();

    const packet = initWithPayload(io, 1, .{
        .request_clip = .{
            .id = 123,
            .format = .{
                .format = .image,
                .mime_type = "image/png",
            },
        },
    });

    const bytes = try Serde.msgpack.toSlice(arena.allocator(), packet);

    const decoded_packet = try Serde.msgpack.fromSlice(Packet, arena.allocator(), bytes);

    try std.testing.expectEqualDeep(packet, decoded_packet);
}

test "check latency" {
    const io = std.testing.io;
    const packet = initWithPayload(io, 1, .{
        .request_clip = .{
            .id = 123,
            .format = .{
                .format = .image,
                .mime_type = "image/png",
            },
        },
    });

    const expected_latency = 15;

    try io.sleep(.fromMilliseconds(expected_latency), .awake);

    const expected: f64 = expected_latency;
    const got: f64 = @floatFromInt(packet.latency(io));

    try std.testing.expectApproxEqRel(
        expected,
        got,
        5.0,
    );
}
